--위시리스트
SELECT 
    W.NO
    , W.MEM_NO
    , W.ROOM_NO
    , R.GRADE
    , R.NAME
    , A.ADDRESS
    , A.IMG_URL
    , R.WEEKDAY_PRICE
    , R.WEEKEND_PRICE
FROM WISH_LIST W
JOIN ROOM R ON W.ROOM_NO = R.NO
JOIN ACCOMMODATION A ON R.ACCOM_NO = A.NO
WHERE W.MEM_NO = '1'
;


SELECT 
    W.NO
    , W.MEM_NO
    , W.ROOM_NO
    , R.GRADE
    , R.NAME
    , A.ADDRESS
    , A.IMG_URL
    , R.WEEKDAY_PRICE
    , R.WEEKEND_PRICE
FROM WISH_LIST W
JOIN ROOM R ON W.ROOM_NO = R.NO
JOIN ACCOMMODATION A ON R.ACCOM_NO = A.NO
WHERE W.MEM_NO = ?
;